// apps/starter-sveltekit/src/routes/+page.svelte
<script lang="ts">
	import type { PageServerData } from './$types';
	export let data: PageServerData;
</script>

<main>
	<header>
		<img src="/flap.gif" alt="Xata Logo" />
		<h1>
			SvelteKit<span aria-hidden>&#8209;</span>Xata<span aria-hidden>&#8209;</span>Starter
		</h1>
	</header>
	<article>
		{#if data.links.length === 0}
			<section>
				<h2>No records found.</h2>
				<strong>
					Create a `svelte_with_xata_example` and push some useful links to see them here.
				</strong>
				<form method="post" action="?/pushRecords">
					<button type="submit">Push records to Xata</button>
				</form>
			</section>{:else}
			<ul>
				{#each data.links as { title, url, description, id }}
					<li>
						<a href={url ?? ''} rel="noopener noreferrer" target="_blank">
							{title}
						</a>
						<p>{description}</p>
						<form method="post" action="?/deleteRecord">
							<input type="hidden" name="id" value={id} />
							<button type="submit">
								<span role="img" aria-label="delete item"> 🗑 </span>
							</button>
						</form>
					</li>
				{/each}
			</ul>
		{/if}
	</article>
	<footer>
		<span>
			Made by{' '}
			<a href="https://xata.io" rel="noopener noreferrer" target="_blank">
				<object data="/xatafly.svg" aria-label="Xata Logo" />
			</a>
		</span>
	</footer>
</main>

<style>
	:global(html) {
		--system-fonts: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial,
			sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
		--xata-accent: rgb(199, 8, 105);
		--xata-accent-faded: rgba(199, 8, 105, 0.4);
		--transition-duration: 350ms;
		--background-color: #000;
		--text-color: #fff;
	}

	:global(body) {
		padding: 0;
		margin: 0;
		min-height: 100vh;
		overflow-x: hidden;
		font-family: 'Inter', var(--system-fonts);
		color: var(--text-color);
		background-color: var(--background-color);
	}

	h1 {
		font-family: monospace;
		font-size: 3rem;
		text-align: center;
	}

	img {
		width: 300px;
	}

	a,
	li {
		transition: all var(--transition-duration) ease-in-out;
	}

	a {
		color: var(--text-color);
		font-size: 2rem;
		text-decoration: none;
	}

	li a[target='_blank']::after {
		content: '↗';
		position: relative;
		top: -1em;
		left: 0.5em;
		font-size: 1rem;
	}

	p {
		color: var(--text-color);
		font-size: 1.2rem;
		line-height: 2;
	}

	main {
		min-height: 100vh;
		display: grid;
		grid-template-rows: auto 1fr auto;
	}

	header,
	footer {
		display: grid;
		place-items: center;
	}

	header {
		height: clamp(4rem, 40rem, 55vh);
	}
	footer {
		border-top: dashed 2px rgba(255, 255, 255, 0.4);
		height: clamp(2rem, 5rem, 10vh);
	}

	section {
		display: grid;
		place-items: center;
		max-width: 70vw;
		padding: 5rem;
		grid-gap: 2rem;
		margin: 5rem auto;
		border-radius: 30px/15px;
		border: dashed 2px var(--xata-accent);
		font-size: 1.2rem;
		text-align: center;
		line-height: 2;
	}

	button {
		background-color: transparent;
		padding: 0.5rem 1rem;
		border: 0;
		color: transparent;
		font-size: 2rem;
		border-radius: 15px;
		transition: all var(--transition-duration) ease-in-out;
		text-shadow: 0 0 var(--text-color);
	}

	button:hover,
	button:focus {
		text-shadow: 0 0 var(--xata-accent);
		border-color: transparent;
	}

	ul {
		max-width: 120ch;
		margin: 0 auto;
		padding: 5rem 2rem;
		display: grid;
		grid-gap: 2rem;
		list-style: none;
	}

	li {
		position: relative;
		padding: 1rem 2rem;
		border: solid 2px var(--text-color);
		border-radius: 10px/5px;
	}

	li:hover a,
	li:focus-within a {
		text-decoration: underline dotted;
		color: var(--xata-accent);
	}

	li form {
		position: absolute;
		top: 0.5rem;
		right: 0.5rem;
	}

	object {
		position: relative;
		top: 10px;
		width: 2rem;
		margin-left: 0.5em;
	}

	@media (min-width: 600px) {
		ul {
			grid-template-columns: 1fr 1fr;
		}
	}

	@media (prefers-color-scheme: light) {
		html {
			--background-color: #fff;
			--text-color: #000;
			--xata-accent: rgb(10, 108, 63);
			--xata-accent-faded: rgba(32, 198, 183, 0.7);
		}

		@media (prefers-reduced-motion) {
			html {
				--transition-duration: 0;
			}
		}
	}
</style>

// apps/remix-minimal/app/routes/index.tsx
import type { FC } from 'react'
import type { ActionFunction, LoaderFunction } from '@remix-run/node'
import { Form, useFetcher, useLoaderData } from '@remix-run/react'
import {
  getXataClient,
  type RemixWithXataExampleRecord,
} from '~/lib/xata.codegen.server'
import { LINKS } from '~/lib/settings'

type TaskComponent = FC<
  Pick<RemixWithXataExampleRecord, 'id' | 'title' | 'url' | 'description'>
>
export const loader: LoaderFunction = async () => {
  const links = await getXataClient().db.remix_with_xata_example.getAll()

  return links
}

export const action: ActionFunction = async ({ request }) => {
  const { action, item } = Object.fromEntries(await request.formData())

  if (action === 'delete' && typeof item === 'string') {
    await getXataClient().db.remix_with_xata_example.delete(item)
    return {}
  }

  if (action === 'create') {
    await getXataClient().db.remix_with_xata_example.create(LINKS)
    return {}
  }
}

const Task: TaskComponent = ({ id, title, url, description }) => {
  const fetcher = useFetcher()

  return fetcher.submission ? null : (
    <li key={url}>
      <a href={url ?? ''} rel="noopener noreferrer" target="_blank">
        {title}
      </a>
      <p>{description}</p>
      <fetcher.Form method="put">
        <input type="hidden" name="action" value="delete" />
        <button type="submit" name="item" value={id}>
          <span role="img" aria-label="delete item">
            🗑
          </span>
        </button>
      </fetcher.Form>
    </li>
  )
}

export default function Index() {
  const links = useLoaderData<RemixWithXataExampleRecord[]>()

  return (
    <main>
      <header>
        <img src="/flap.gif" alt="Xata Logo" />
        <h1>
          Remix with<span aria-hidden>&#8209;</span>xata
        </h1>
      </header>
      <article>
        {links.length > 0 ? (
          <ul>
            {links.map((link) => (
              <Task key={link.id} {...link} />
            ))}
          </ul>
        ) : (
          <section>
            <h2>No records found.</h2>
            <strong>
              Create a `remix_with_xata_example` and push some useful links to
              see them here.
            </strong>
            <Form method="post">
              <input type="hidden" name="action" value="create" />
              <button type="submit">Push records to Xata</button>
            </Form>
          </section>
        )}
      </article>
      <footer>
        <span>
          Made by{' '}
          <a href="https://xata.io" rel="noopener noreferrer" target="_blank">
            <object data="/xatafly.svg" aria-label="Xata Logo" />
          </a>
        </span>
      </footer>
    </main>
  )
}
